name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'drop'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'bool'
        required: false
        type: boolean
#      environment:
 #       description: 'env'
  #      type: environment
   #     required: truejobs
jobs:
  letknow:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C yourusername@company; ssh -i ~/.ssh/id_ed25519 abcxyz"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1