name: CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'drop'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'bool'
        required: false
        type: boolean
#      environment:
 #       description: 'env'
  #      type: environment
   #     required: truejobs
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v2
    - name: https://www.rust-lang.org/tools/install
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: https://github.com/lhotari/action-upterm/issues/9
      run: echo "ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C yourusername@company"; echo "ssh -i ~/.ssh/id_ed25519 "
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1